import React, { useState } from 'react';
import type { PropertyRecord, RentRecord } from '../types';
import { formatCurrency } from '../utils/calculations';
import { PROPERTY_TYPE_CONFIG, RENTED_CATEGORY_CONFIG } from '../utils/deadlinesColorMap';

interface RealEstateDonutChartProps {
  properties: PropertyRecord[];
  rents: RentRecord[];
  selectedCategory: string;
  onSelectCategory: (category: string) => void;
}

interface DistributionCategory {
  id: 'Land' | 'Commercial Property' | 'Private House' | 'Rented';
  filterKey: string;
  name: string;
  icon: string;
  color: string;
  value: number;
  count: number;
  percentage?: number;
  isRentalIncome?: boolean;
}

export const RealEstateDonutChart: React.FC<RealEstateDonutChartProps> = ({
  properties,
  rents,
  selectedCategory,
  onSelectCategory
}) => {
  const [hoveredCategory, setHoveredCategory] = useState<DistributionCategory | null>(null);

  // Active properties only (exclude SOLD and DELETED)
  const activeProperties = properties.filter((p) => p.property_status === 'ACTIVE');

  // Set of property IDs that currently have an active rent
  const activeRents = rents.filter((r) => r.is_active);
  const rentedPropertyIds = new Set(
    activeRents.map((r) => r.p_id)
  );

  let landVal = 0, landCount = 0;
  let commercialVal = 0, commercialCount = 0;
  let privateHouseVal = 0, privateHouseCount = 0;
  let rentedCount = 0;

  activeProperties.forEach((p) => {
    const val = Number(p.purchase_price) || 0;
    if (rentedPropertyIds.has(p.p_id)) {
      rentedCount += 1;
    }
    if (p.p_type === 'LAND' || p.p_type === 'Land') {
      landVal += val;
      landCount += 1;
    } else if (p.p_type === 'COMMERCIAL_PROPERTY' || p.p_type === 'Commercial Property') {
      commercialVal += val;
      commercialCount += 1;
    } else {
      privateHouseVal += val;
      privateHouseCount += 1;
    }
  });

  const totalActiveValue = landVal + commercialVal + privateHouseVal;

  // Total Monthly Rental Income generated by all rented properties
  const totalMonthlyRentalIncome = activeRents.reduce(
    (sum, r) => sum + (Number(r.rent_amount) || 0),
    0
  );

  const categories: DistributionCategory[] = [
    {
      id: 'Land',
      filterKey: 'land',
      name: PROPERTY_TYPE_CONFIG['Land'].label,
      icon: PROPERTY_TYPE_CONFIG['Land'].icon,
      color: PROPERTY_TYPE_CONFIG['Land'].color,
      value: landVal,
      count: landCount,
      percentage: totalActiveValue > 0 ? (landVal / totalActiveValue) * 100 : 0
    },
    {
      id: 'Commercial Property',
      filterKey: 'commercial',
      name: PROPERTY_TYPE_CONFIG['Commercial Property'].label,
      icon: PROPERTY_TYPE_CONFIG['Commercial Property'].icon,
      color: PROPERTY_TYPE_CONFIG['Commercial Property'].color,
      value: commercialVal,
      count: commercialCount,
      percentage: totalActiveValue > 0 ? (commercialVal / totalActiveValue) * 100 : 0
    },
    {
      id: 'Private House',
      filterKey: 'private-house',
      name: PROPERTY_TYPE_CONFIG['Private Properties']?.label || 'Private Properties',
      icon: PROPERTY_TYPE_CONFIG['Private Properties']?.icon || '🏡',
      color: PROPERTY_TYPE_CONFIG['Private Properties']?.color || '#2563EB',
      value: privateHouseVal,
      count: privateHouseCount,
      percentage: totalActiveValue > 0 ? (privateHouseVal / totalActiveValue) * 100 : 0
    },
    {
      id: 'Rented',
      filterKey: 'rented',
      name: RENTED_CATEGORY_CONFIG.label,
      icon: RENTED_CATEGORY_CONFIG.icon,
      color: RENTED_CATEGORY_CONFIG.color,
      value: totalMonthlyRentalIncome,
      count: rentedCount,
      percentage: 0,
      isRentalIncome: true
    }
  ];

  const radius = 78;
  const circumference = 2 * Math.PI * radius;

  let accumulatedOffset = 0;
  // Chart slices display the physical asset valuation distribution (Land, Commercial, Private House)
  const chartCategories = categories.filter((c) => !c.isRentalIncome);
  const slices = chartCategories.map((cat) => {
    const pct = cat.percentage ?? 0;
    const sliceLength = (pct / 100) * circumference;
    const strokeGap = Math.max(0, circumference - sliceLength);
    const offset = accumulatedOffset;
    accumulatedOffset += sliceLength;
    return {
      ...cat,
      sliceLength,
      strokeGap,
      offset
    };
  });

  const activeCategory = hoveredCategory || categories.find((c) => c.filterKey === selectedCategory.toLowerCase());
  const activeValue = activeCategory ? activeCategory.value : totalActiveValue;
  const activePct = totalActiveValue > 0 ? ((activeValue / totalActiveValue) * 100).toFixed(1) : '0';

  return (
    <div className="chart-layout-grid" style={{ marginTop: '4px' }}>
      {/* SVG Donut Visual */}
      <div className="donut-visual-container">
        <svg className="donut-svg" viewBox="0 0 240 240">
          <circle
            cx="120"
            cy="120"
            r={radius}
            fill="none"
            stroke="#F1F5F9"
            strokeWidth="22"
          />

          {slices.map((slice) => {
            if (slice.value <= 0) return null;
            const isHovered = hoveredCategory?.id === slice.id;
            return (
              <circle
                key={slice.id}
                cx="120"
                cy="120"
                r={radius}
                fill="none"
                stroke={slice.color}
                strokeWidth={isHovered ? 26 : 20}
                strokeDasharray={`${slice.sliceLength} ${slice.strokeGap}`}
                strokeDashoffset={-slice.offset}
                strokeLinecap="butt"
                className="donut-slice-path"
                onMouseEnter={() => setHoveredCategory(slice)}
                onMouseLeave={() => setHoveredCategory(null)}
                onClick={() => onSelectCategory(slice.filterKey)}
                style={{
                  cursor: 'pointer',
                  transition: 'stroke-width 0.2s ease, opacity 0.2s ease',
                  opacity: hoveredCategory && hoveredCategory.id !== slice.id ? 0.5 : 1
                }}
              />
            );
          })}
        </svg>

        <div className="donut-center-info">
          <span className="donut-center-name">{hoveredCategory ? activeCategory?.name : 'Active Real Estate'}</span>
          <div className="donut-center-value">
            ₹ {formatCurrency(hoveredCategory ? activeValue : totalActiveValue)}
            {hoveredCategory?.isRentalIncome && (
              <span style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-muted)' }}>/mo</span>
            )}
          </div>
          <div className="donut-center-pct">
            {hoveredCategory?.isRentalIncome
              ? `Total Monthly Income (${rentedCount} active ${rentedCount === 1 ? 'lease' : 'leases'})`
              : hoveredCategory
              ? `${activePct}% of Total`
              : `${activeProperties.length} Properties`}
          </div>
        </div>
      </div>

      {/* Category Tiles Grid */}
      <div className="category-cards-grid" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
        {categories.map((cat) => {
          const isSelected = selectedCategory.toLowerCase() === cat.filterKey.toLowerCase();
          const isHovered = hoveredCategory?.id === cat.id;

          return (
            <div
              key={cat.id}
              className={`category-tile clickable ${isSelected ? 'selected' : ''}`}
              style={{
                '--cat-color': cat.color,
                borderColor: isSelected ? cat.color : isHovered ? cat.color : undefined,
                background: isSelected ? 'var(--bg-surface-subtle)' : undefined,
                transform: isHovered || isSelected ? 'translateY(-2px)' : undefined,
                boxShadow: isSelected ? `0 4px 12px ${cat.color}25` : undefined
              } as React.CSSProperties}
              onMouseEnter={() => setHoveredCategory(cat)}
              onMouseLeave={() => setHoveredCategory(null)}
              onClick={() => onSelectCategory(isSelected ? 'all' : cat.filterKey)}
            >
              <div className="category-tile-head">
                <div className="category-icon-title">
                  <span className="category-icon">{cat.icon}</span>
                  <span className="category-title" style={{ fontSize: '14px' }}>{cat.name}</span>
                </div>
                <span
                  className="category-badge-pill"
                  style={{
                    background: `${cat.color}15`,
                    color: cat.color,
                    fontWeight: 700
                  }}
                >
                  {cat.count} {cat.count === 1 ? 'Prop' : 'Props'}
                </span>
              </div>

              <div className="category-amount-row" style={{ marginTop: '12px' }}>
                <span className="category-amount-val" style={{ fontSize: '18px' }}>
                  ₹ {formatCurrency(cat.value)}
                  {cat.isRentalIncome && (
                    <span style={{ fontSize: '11px', fontWeight: 600, color: 'var(--text-muted)', marginLeft: '3px' }}>
                      /mo
                    </span>
                  )}
                </span>
                {cat.isRentalIncome ? (
                  <span
                    className="category-pct-val"
                    style={{
                      color: cat.color,
                      fontSize: '11px',
                      fontWeight: 700,
                      background: `${cat.color}15`,
                      padding: '2px 6px',
                      borderRadius: 'var(--radius-sm)'
                    }}
                  >
                    Monthly Income
                  </span>
                ) : (
                  <span className="category-pct-val" style={{ color: cat.color }}>
                    {(cat.percentage ?? 0).toFixed(1)}%
                  </span>
                )}
              </div>

              <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '6px' }}>
                {isSelected
                  ? cat.isRentalIncome
                    ? '✓ Showing rented properties'
                    : '✓ Showing this category'
                  : cat.isRentalIncome
                  ? 'Click to filter rented properties'
                  : 'Click to filter'}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
